name: lexicon update

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '30 3 * * *' #UTC

jobs:
  lexicon:
    name: lexicon update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: latest
          extensions: 'mbstring'
          coverage: none
      - name: submodule update
        run: git submodule update --remote
      - name: Install Composer dependencies
        run: composer install -q
        working-directory: ./command
      - name: lexicon update
        run: composer run lexicon
        working-directory: ./command
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: 'lexicon'
          commit-message: 'lexicon update'
          title: 'lexicon update'
          body: 'lexicon update'
