name: lexicon update

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '30 3 * * *' #UTC

jobs:
  lexicon:
    name: lexicon update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8.4'
          extensions: 'mbstring'
          coverage: none
      - name: submodule update
        run: git submodule update --remote
      - name: Install Composer dependencies
        run: composer install -q
        working-directory: ./command
      - name: lexicon update
        run: composer run lexicon
        working-directory: ./command
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7 #https://github.com/peter-evans/create-pull-request
        with:
          branch: 'lexicon'
          commit-message: 'lexicon update'
          title: 'lexicon update'
          body: 'lexicon update'
